AIFF_SAMPLE_RATE = 44100
AIFF_BIT_DEPTH = 16
AIFF_SAMPLE_FORMAT = "s16"
AIFF_CODEC = "pcm_s16be"

MP3_SAMPLE_RATE = 44100
MP3_SAMPLE_FORMAT = "s16p"
MP3_CODEC = "libmp3lame"
MP3_BITRATE = "320k"

# FFmpeg configuration
FFMPEG_LOG_LEVEL = "error"

# Metadata configuration
ID3_VERSION = 3
ID3_ENCODING = 3