name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            artifact_name: trackonverter-windows.exe
            artifact_path: dist/trackonverter.exe
          - os: macos-latest
            platform: macos
            artifact_name: trackonverter-macos.zip
            artifact_path: trackonverter-macos.zip
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Poetry
      run: pipx install poetry
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    
    - name: Build with PyInstaller
      run: poetry run pyinstaller trackonverter.spec
    
    - name: Package macOS App Bundle
      if: matrix.platform == 'macos'
      run: |
        cd dist
        zip -r ../trackonverter-macos.zip Trackonverter.app
        cd ..
    
    - name: Rename Windows executable
      if: matrix.platform == 'windows'
      run: |
        move dist\trackonverter.exe dist\trackonverter-windows.exe
      shell: cmd
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }}
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.artifact_path }}
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}